---
Approximate cost:
  type: String
  required: "false"
  value: ""
Bioinformatician:
  type: String
  required: "false"
  value: ""
Coverage:
  type: Numeric
  required: "false"
  value: ""
Depth:
  type: String
  required: "false"
  value: ""
Description:
  type: Text
  required: "false"
  value: ""
Email:
  type: String
  required: "true"
  value: ""
Fragment Size:
  type: String
  required: "false"
  value: ""
Funding source:
  type: String
  required: "true"
  value: ""
Genome build:
  type: String
  required: "false"
  value: ""
Library Prep Method:
  type: String
  required: "false"
  value: ""
Number of experiments (total number of cells):
  type: String
  required: "false"
  value: ""
Prep Kit:
  type: String
  required: "false"
  value: ""
Project type:
  type: String
  required: "true"
  value: ""
Read Length:
  type: Numeric
  required: "false"
  value: ""
Run Type:
  type: String
  required: "false"
  value: ""
Sample quota:
  type: Numeric
  required: "true"
  value: ""
Sequencer type:
  type: String
  required: "true"
  value: ""
Test ID:
  type: String
  required: "false"
  value: ""
...
