'Approximate cost':
'Bioinformatician': 
'Budget Code': 
'Number of experiments (total number of cells)': 
'Coverage': 
'Depth': 
'Description': 
'Email': 
'Fragment Size': 
'Funding source': 
'Genome build': 
'Library Prep Method': 
'Prep Kit': 
'Project type':
'Read Length':
'Run Type':
'Sample quota':
'Sequencer type':
'Test ID':
