---
10x Application:
  type: String
  required: "false"
  value: ""
Ampliseq Primer Design ID (IAD number):
  type: String
  required: "false"
  value: ""
ASF Comments:
  type: String
  required: "false"
  value: ""
Average Size (bp):
  type: Numeric
  required: "false"
  value: ""
C1 Application:
  type: String
  required: "false"
  value: ""
C1 IFC Used:
  type: String
  required: "false"
  value: ""
Cells loaded:
  type: String
  required: "false"
  value: ""
Coverage (x):
  type: String
  required: "false"
  value: ""
Custom Index Primer:
  type: String
  required: "false"
  value: ""
Custom Index Primer Concentration (uM):
  type: Numeric
  required: "false"
  value: ""
Custom Seq Primer:
  type: String
  required: "false"
  value: ""
Custom Seq Primer Concentration (uM):
  type: Numeric
  required: "false"
  value: ""
End Type:
  type: String
  required: "false"
  value: ""
Freezerworks Barcode:
  type: String
  required: "false"
  value: ""
Hybridisation baits:
  type: String
  required: "false"
  value: ""
Index1 (i7):
  type: String
  required: "false"
  value: ""
Index2 (i5):
  type: String
  required: "false"
  value: ""
Library band size (bp):
  type: String
  required: "false"
  value: ""
Library Preparation Protocol:
  type: String
  required: "false"
  value: ""
Number of primer pairs in pool:
  type: String
  required: "false"
  value: ""
PEACE-Tx Patient ID:
  type: String
  required: "false"
  value: ""
Pool ID:
  type: String
  required: "false"
  value: ""
Primer pairs:
  type: String
  required: "false"
  value: ""
Progress:
  type: String
  required: "false"
  value: ""
Project ID:
  type: String
  required: "false"
  value: ""
Read Length:
  type: String
  required: "false"
  value: ""
Reference Genome:
  type: String
  required: "false"
  value: ""
RIN:
  type: Numeric
  required: "false"
  value: ""
RNA Type:
  type: String
  required: "false"
  value: ""
Sample Concentration (ng/uL):
  type: Numeric
  required: "false"
  value: ""
Sample Molarity 1 (nM):
  type: Numeric
  required: "false"
  value: ""
Sample Molarity 2 (nM):
  type: Numeric
  required: "false"
  value: ""
Sample Molarity Average (nM):
  type: Numeric
  required: "false"
  value: ""
Sample Type:
  type: String
  required: "false"
  value: ""
Sequencer:
  type: String
  required: "false"
  value: ""
Sequencing required (million reads):
  type: Numeric
  required: "false"
  value: ""
Size Selection (bp):
  type: String
  required: "false"
  value: ""
Submitted Material:
  type: String
  required: "false"
  value: ""
Test ID:
  type: String
  required: "false"
  value: ""
Total Amount (ng):
  type: Numeric
  required: "false"
  value: ""
User Comments:
  type: String
  required: "false"
  value: ""
User Pool ID:
  type: String
  required: "false"
  value: ""
User Sample Name:
  type: String
  required: "false"
  value: ""
Volume (uL):
  type: Numeric
  required: "false"
  value: ""
...
