'Ampliseq Primer Design ID (IAD number)': 
'ASF Comments': 
'C1 Application': 
'C1 IFC Used': 
'Coverage (x)': 
'Custom Index Primer': 
'Custom Index Primer Concentration (uM)': 
'Custom Seq Primer': 
'Custom Seq Primer Concentration (uM)': 
'End Type': 
'Hybridisation baits': 
'i5 Index': 
'i7 Index': 
'Library band size (bp)': 
'Library Preparation Protocol': 
'Number of primer pairs in pool': 
'Pool ID': 
'Primer pairs': 
'Progress': 
'Read Length': 
'Reference Genome': 
'RIN': 
'RNA Type': 
'Sample Concentration (ng/uL)': 
'Sample Type': 
'Sequencer': 
'Sequencing required (million reads)': 
'Size Selection (bp)': 
'Test ID': 
'Total Amount (ng)': 
'TRACERx Sample ID': 
'User Comments': 
'User Sample Name': 
'Volume (uL)': 
